---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: setiathomedata
  namespace: boinc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: setiathome
  namespace: boinc
  labels:
    app: setiathome
spec:
  replicas: 1
  template:
    metadata:
      name: setiathome
      namespace: boinc
      labels:
        app: setiathome
    spec:
      containers:
        - name: setiathome
          image: lscr.io/linuxserver/boinc:latest
          imagePullPolicy: Always
          env:
          - name: TZ
            value: "America/Denver"
          - name: BOINC_GUI_RPC_PASSWORD
            value: "password123456"
          - name: BOINC_CMD_LINE_OPTIONS
            value: "--allow_remote_gui_rpc"
          volumeMounts:
            - mountPath: /var/lib/boinc
              name: setiathomedata
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
          - containerPort: 31416
            name: manager
            protocol: TCP
      volumes:
        - name: setiathomedata
          persistentVolumeClaim:
            claimName: setiathomedata
  selector:
    matchLabels:
      app: setiathome
---
apiVersion: v1
kind: Service
metadata:
  name: setiathome
  namespace: boinc
  #annotations:
    #metallb.universe.tf/address-pool: default
spec:
  selector:
    app: setiathome
  ports:
    - port: 80
      name: http
      protocol: TCP
    - port: 443
      name: https
      protocol: TCP
    - port: 31416
      name: manager
      protocol: TCP
  type: LoadBalancer