---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rosettaathomedata
  namespace: boinc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rosettaathome
  namespace: boinc
  labels:
    app: rosettaathome
spec:
  replicas: 1
  template:
    metadata:
      name: rosettaathome
      namespace: boinc
      labels:
        app: rosettaathome
    spec:
      containers:
        - name: rosettaathome
          image: boinc/client:arm64v8
          imagePullPolicy: Always
          env:
          - name: TZ
            value: "America/Denver"
          - name: BOINC_GUI_RPC_PASSWORD
            value: "password123456"
          - name: BOINC_CMD_LINE_OPTIONS
            value: "--allow_remote_gui_rpc"
          volumeMounts:
            - mountPath: /var/lib/boinc
              name: rosettaathomedata
          ports:
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
          - containerPort: 31416
            name: manager
            protocol: TCP
      nodeName: node03
      volumes:
        - name: rosettaathomedata
          persistentVolumeClaim:
            claimName: rosettaathomedata
  selector:
    matchLabels:
      app: rosettaathome
---
apiVersion: v1
kind: Service
metadata:
  name: rosettaathome
  namespace: boinc
  #annotations:
    #metallb.universe.tf/address-pool: default
spec:
  selector:
    app: rosettaathome
  ports:
    - port: 80
      name: http
      protocol: TCP
    - port: 443
      name: https
      protocol: TCP
    - port: 31416
      name: manager
      protocol: TCP
  type: LoadBalancer